### ISSUE TITLE
No output for mkcat <filename>

### ISSUE THREAD

**Issue by chocolateboy** [mkdoc/mkdoc#1]
<table>
<tr><th align="left">mkdoc</th><td>1.0.49, 1.0.50</td></tr>
<tr><th align="left">mkcat</th><td>1.1.5</td></tr>
<tr><th  align="left">node</th><td>v10.1.0, v10.4.1</td></tr>
<tr><th  align="left">OS</th><td>Linux (Arch)</td></tr>
</table>

The README states that the usage for mkcat is:

```bash
$ mkcat file.md | mkout --xml
```

But it appears to ignore the filename argument, and produces no output:

```bash
$ mkcat file.md | wc -l
0
```

This works:

```bash
$ cat file.md | mkcat
```

So I would expect this to work as well:

```bash
$ mkcat < file.md
```

\- which it does, in part (it produces the expected output), but it also dies with an error:

```
node_modules/mkdoc/cli/cat.js:70
      process.stdin.end();
                    ^

TypeError: process.stdin.end is not a function
    at StreamCaller.done (node_modules/mkdoc/cli/cat.js:70:21)
    at Object.onceWrapper (events.js:273:13)
    at StreamCaller.emit (events.js:182:13)
    at done (node_modules/mkdoc/node_modules/mkcat/index.js:121:13)
    at StreamCaller.<anonymous> (node_modules/mkdoc/node_modules/mkcat/index.js:169:5)
    at Object.onceWrapper (events.js:273:13)
    at StreamCaller.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:644:14)
    at endWritable (_stream_writable.js:652:3)
    at StreamCaller.Writable.end (_stream_writable.js:592:5)
```

**Comment by chocolateboy** [comment]
Moved to https://github.com/mkdoc/mkcat/issues/1
